### ISSUE TITLE
Build Simulator Excutable in the correct Host Architecture

### ISSUE THREAD

**Issue by below** [usabilla/usabilla-u4a-react-native#193]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `usabilla-react-native@1.0.0` for the project I'm working on.

In the early days of M1 Macs, some libraries were not available for the ARM64 Simulator. This is why, to solve a symptom, not a cause, people excluded the ARM64 architecture from their simulator builds, and used Rosetta to run an x86_64 variant.

This was the case for Usabilla, too. And the Podspec flags are carried on to the target app.

In 2023, these issues should be fixed, and we can not rely on Rosetta being around forever, so the Simulator on an ARM64 Mac should use an ARM64 binary. There is no reason to exclude it anymore.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/usabilla-react-native/usabilla-react-native.podspec b/node_modules/usabilla-react-native/usabilla-react-native.podspec
index 85a2c08..3e0928d 100644
--- a/node_modules/usabilla-react-native/usabilla-react-native.podspec
+++ b/node_modules/usabilla-react-native/usabilla-react-native.podspec
@@ -18,7 +18,4 @@ Pod::Spec.new do |s|
 
   s.dependency 'React'
   s.dependency 'Usabilla', '~> 6.5'
-  
-  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
-  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
 end
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jerfranco-deloitte** [comment]
May I know when are we going to apply this fix? I'm getting this error below when I'm running my react native on an iPhone 14 Pro simulator and the fix mentioned above will solve this issue:
<img width="450" alt="image" src="https://github.com/usabilla/usabilla-u4a-react-native/assets/101161142/c4075c37-b78b-4306-9a8b-85144551bf97">

It took me hours to figure out what was causing the issue and I just discovered it when I ran my app directly in xcode. It turns out that adding `'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'` into the podspec forces the app to be built for Rosetta:
<img width="450" alt="image" src="https://github.com/usabilla/usabilla-u4a-react-native/assets/101161142/a9df7fda-6efa-4776-a85d-dfac353ccdac">

Apple is now discouraging developers the use of Rosetta and as mentioned above, we can not rely on Rosetta being around forever. I hope the suggested changes to fix this issue will finally be added to the codebase soon.

**Comment by henrique-c-ladeira-dti** [comment]
I also faced the same issue, I had to take those lines out to build on M1 macs.

We also spent several hours trying to figure out what was the problem with those builds.

Please patch it soon, the solution's already been given.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
