### ISSUE TITLE
Unable to implement usabilla

### ISSUE THREAD

**Issue by chrisverra** [usabilla/usabilla-u4a-react-native#33]
I am on:

- react-native-cli: 2.0.1
- react-native: 0.53.0
- Xcode 9.3 (9E124)

At the additional setup part for iOS, it states the following:

The app compiles, but when i call: usabilla.loadFeedbackForm("YOUR_FORM_ID_HERE")
with my id, after also adding the require, it says `Native module cannot be null`

```
const usabilla = require('usabilla-react-native');
usabilla.loadFeedbackForm('my id is in here')
```
![simulator screen shot - iphone 8 plus - 2018-05-23 at 14 04 58](https://user-images.githubusercontent.com/6358353/40423275-59bc74b8-5e92-11e8-980e-4388ac1e509a.png)

<img width="1151" alt="screen shot 2018-05-23 at 14 00 39" src="https://user-images.githubusercontent.com/6358353/40423096-be653f5e-5e91-11e8-9657-734f355908ea.png">
<img width="1154" alt="screen shot 2018-05-23 at 14 00 28" src="https://user-images.githubusercontent.com/6358353/40423097-be83229e-5e91-11e8-8538-c6bbae35b166.png">
<img width="250" alt="screen shot 2018-05-23 at 14 00 14" src="https://user-images.githubusercontent.com/6358353/40423098-be9c20d2-5e91-11e8-93e2-1dfe90d64621.png">

I decided to add the project to the Libraries btw.

Hope you can help me out.

Cheers

**Comment by chrisverra** [comment]
Apologies, I have used initialize. I guess I forgot to mention.
Are there any extensive docs for this package? 

I've read in another issue that somebody used a run script and that it would be updated in the docs. However I am not able to find these docs. (could be that it was for native only docs)

Thanks so far

**Comment by Rifinio** [comment]
Hello @chrisverra, 
It's really hard to pinpoint exactly where this goes wrong for you! The documentation is on the [readme](https://github.com/usabilla/usabilla-u4a-react-native#installation) page.

However, I can point some steps to verify and see if they fix your problem:
1) After installing the Usabilla SDK via npm you have to link it to your project using `react-native link usabilla-react-native`.

2) `Framework Search Paths` can be found as follows:
![xcode-steps](https://user-images.githubusercontent.com/917876/40650473-aa3df466-6333-11e8-96ff-8ac44b43877e.jpg)

3) Clone the react-native project from here `https://github.com/usabilla/usabilla-u4a-react-native.git`
- Enter UsabillaSampleApp and do `npm install`
- Open the ios project in` /UsabillaSampleApp/ios/RNUsabilla.xcodeproj` and run it.
This is a sample project so it should run and show an app then you can change your app-id and form-id in the App.js to test. 

Best,

**Comment by chrisverra** [comment]
I am able to run the sample app. However, I must miss something in the setup of the sdk in our own app.

I have done:
`npm install usabilla-react-native
`
followed by:
`react-native link usabilla-react-native
`

- Created a bridging header ( added a swift file so it automatically does that)
- Added the framework search path as described
- Created a copy files phase in build phases as described.

In JS I have imported the package, called the initialize app etc but i still get the "Native module cannot be null"

I fail to see what step I am missing


![screen shot 2018-06-07 at 15 41 10](https://user-images.githubusercontent.com/6358353/41103399-57569374-6a69-11e8-9c1b-4146d7d1095b.png)
![screen shot 2018-06-07 at 15 40 55](https://user-images.githubusercontent.com/6358353/41103400-577fbb78-6a69-11e8-92c5-476bc9b9de7d.png)
![screen shot 2018-06-07 at 15 40 42](https://user-images.githubusercontent.com/6358353/41103401-57a11408-6a69-11e8-801a-561e48dfbce4.png)

**Comment by tzengerink** [comment]
@chrisverra Is this still relevant for you?

**Comment by MokumJ** [comment]
@tzengerink I took over the task from the issuer and I can confirm that this is still an issue.

**Comment by torkvell** [comment]
Sample app tested and works: https://github.com/usabilla/usabilla-u4a-react-native/tree/master/UsabillaSampleApp

**Comment by arled** [comment]
Getting the same thing even after following the steps in the readme. and why doesn't this have a podspec?!

**Comment by UsabillaSupport** [comment]
Hi Arled,


Thank you for your message! 


Our SDK developers are currently reviewing the implementation process for the React Native bridge to see if this error still persists. Just to confirm, did ran into the "native module cannot be null" error when adding the bridge to your own project? Or was this an issue with the Sample app?


Thanks, and I look forward to hearing from you!


Danny

Best regards,


Danny Graugnard
Technical Success Specialist
Customer Success NYC
support@usabilla.com | +31 20 261 63 33
Usabilla | Rokin 16 | 1012 KR | Amsterdam


Book time with me here!


Did you know that Usabilla has a dedicated Support Center with detailed guides, information, FAQs, and Tip&Tricks for using Usabilla? 
You can find our Support Center on https://support.usabilla.com


How would you rate this email?

--- original message ---
On August 13, 2019, 12:18 PM EDT notifications@github.com wrote:


Getting the same thing even after following the steps in the readme. and why doesn't this have a podspec?!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
