### ISSUE TITLE
Update packaged Usabilla.framework for Xcode 11

### ISSUE THREAD

**Issue by bdolmar** [usabilla/usabilla-u4a-react-native#75]
Xcode 11 updates the Swift compiler from 5.0.1 to 5.1. Attempting to use this package with Xcode 11 results in the following compile error: 

"module compiled with swift 5.0.1 cannot be imported by the swift 5.1 compiler"

The error can be resolved by replacing the `Usabilla.framework` with the version available in the `Xcode-11-GM` tag available from https://github.com/usabilla/usabilla-u4a-ios-swift-sdk

Note: Xcode 11 is no longer in beta or GM but has been released through the public App Store.

**Comment by bdolmar** [comment]
I need to test it, but it looks like this issue was addressed in the following commit (which is available as a part of 0.8.3):

https://github.com/usabilla/usabilla-u4a-react-native/commit/b13999287b8408001db591e39c3f73337feee185

**Comment by torkvell** [comment]
Hi @bdolmar,

This happens due to a difference in the compiler version used for our SDK and the compiler version you have in your Xcode you're trying to build with. To fix this you have to make sure the ```Usabilla.framework``` file is compiled with the same compiler you have on your end. You can find the correctly compiled version in our iOS repository for each release, in your case v6.4.2:
![2019-11-07 at 12 30](https://user-images.githubusercontent.com/40064170/68385564-5d2aec80-015a-11ea-85c0-f2b3f2209ddf.png)
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

To know which version the framework file are build with you can inspect the Swift header file:
![2019-11-07 at 12 30](https://user-images.githubusercontent.com/40064170/68385594-6a47db80-015a-11ea-8cf5-1be4c5617970.png)

You then have to replace the downloaded framework file with the one you have locally.

I hope this helps you in moving forward. If there is anything else we can assist with, please let us know.
